"""Added account table

Revision ID: b76743866c22
Revises: 
Create Date: 2021-07-23 08:33:38.917255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b76743866c22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_2')
    op.add_column('contacts', sa.Column('updated_again', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'updated_again')
    op.create_table('users_2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('last_purchase_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('discount_club', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_2_pkey'),
    sa.UniqueConstraint('username', name='users_2_username_key')
    )
    # ### end Alembic commands ###
